"""message client id

Revision ID: 8a402050fef3
Revises: 92db05fd4aa3
Create Date: 2026-10-09 17:43:19.257823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a402050fef3'
down_revision: Union[str, Sequence[str], None] = '92db05fd4aa3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_message_id', sa.String(length=64), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_messages_conversation_id_client_message_id'), ['conversation_id', 'client_message_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_messages_conversation_id_client_message_id'), type_='unique')
        batch_op.drop_column('client_message_id')

    # ### end Alembic commands ###
