from datetime import datetime

from pydantic import BaseModel, ConfigDict, Field, field_validator

from app.models.conversation import AnswerStatus, ConversationStatus, MessageRole
from app.models.feedback import FeedbackRating
from app.schemas.common import PageParams


class ConversationCreate(BaseModel):
    model_config = ConfigDict(extra="forbid")

    title: str | None = Field(default=None, max_length=200)


class ConversationRead(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    id: int
    title: str
    status: ConversationStatus
    created_at: datetime
    updated_at: datetime
    message_count: int = 0
    last_message_preview: str | None = None


class ConversationListParams(PageParams):
    search: str | None = Field(default=None, max_length=100)
    status: ConversationStatus | None = None


class SourceRead(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    rank: int = Field(description="The [n] number used in the answer text")
    document_id: int | None = Field(description="Null if the document was deleted later")
    document_name: str
    page_number: int | None
    section: str | None
    snippet: str
    score: float


class FeedbackSummary(BaseModel):
    rating: FeedbackRating
    comment: str | None


class TicketReference(BaseModel):
    id: int
    ticket_number: str
    status: str


class MessageRead(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    id: int
    role: MessageRole
    content: str
    answer_status: AnswerStatus | None
    created_at: datetime
    sources: list[SourceRead] = []
    # The current user's rating of this answer, if any.
    feedback: FeedbackSummary | None = None
    # Set on escalation notices: the ticket the question was forwarded to.
    ticket: TicketReference | None = None


class ConversationDetail(ConversationRead):
    customer_id: int
    messages: list[MessageRead]


class MessageCreate(BaseModel):
    model_config = ConfigDict(extra="forbid")

    content: str = Field(min_length=1)
    # Generated by the client; resending with the same id never creates a duplicate.
    client_message_id: str | None = Field(default=None, max_length=64, pattern=r"^[A-Za-z0-9_-]+$")
    category: str | None = Field(default=None, max_length=50, description="Optional knowledge-base filter")

    @field_validator("content")
    @classmethod
    def _strip(cls, value: str) -> str:
        value = value.strip()
        if not value:
            raise ValueError("Message cannot be empty")
        return value


class ChatTurnRead(BaseModel):
    conversation: ConversationRead
    customer_message: MessageRead
    assistant_message: MessageRead | None


class SystemInfo(BaseModel):
    llm_provider: str
    embedding_provider: str
    demo_mode: bool = Field(description="True when answers are quoted from documents without an AI model")
    answer_model: str
    max_question_length: int
